# Generated by Django 4.1.5 on 2023-10-24 19:12

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0007_facebookresponce_typee'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='options',
            field=jsonfield.fields.JSONField(default='blank'),
        ),
    ]
